- name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          # Point this directly to the folder containing your JAR
          appSourcePath: ${{ github.workspace }}/target
          acrName: ca46455e5914acr
          resourceGroup: coupon-bot-rg
          containerAppName: coupon-saver-app
          containerAppEnvironment: managedEnvironment-couponbotrg-aad5
          targetPort: 8080
          runtime: java
